runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /h/.*
  script: change_notification_client.app

- url: /tasks/.*
  script: spec.main.app
  login: admin

- url: /.*
  script: validation.main.app
