runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /blobstore.*
  script: blobstore.app

- url: /ch/
  script: main.app

- url: /index.html
  static_files: www/index.html
  upload: www/index.html
  application_readable: true

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)
  application_readable: true
