runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  script: main.app

- url: /blobstore.*
  script: blobstore.app

- url: /h/index.html
  static_files: www/index.html
  upload: www/index.html
  application_readable: true

- url: /h/(.*)
  static_files: www/\1
  upload: www/(.*)
  application_readable: true
